### ISSUE TITLE
Modify Rename.md to include a 'how to' run the project

### ISSUE THREAD

**Issue by willsoares** [carolinaknoll/awesome-gamified#1]
The _Readme.md_ file doesn't have any information about which frameworks and how to run the project. It could be useful these informations on Readme.

**Comment by carolinaknoll** [comment]
Nice catch! I will look into adding this info as soon as possible later today. Thank you for your contribution! 😄

**Comment by carolinaknoll** [comment]
Just finished adding run instructions, as you requested. 

The readme file is fairly simple now, but I will look into making it better later this evening after my dentist appointment. 

I will be closing this for now. Thank you for your issue. 😄
