### ISSUE TITLE
[SavedItems] Add import/export saved items functionality

### ISSUE THREAD

**Issue by carolinaknoll** [carolinaknoll/awesome-gamified#10]
As saved items are only saved on localStorage, it would be great to have a way to export/import saved items. 

This functionality can be divided into multiple pull requests. As an example: 
- one for exporting items, 
- one for importing items, 
- and possibly, one for importing items that adds a popup with three buttons, asking: 'Discard existing saved items on localStorage?', 'Import new items and keep existing items?', and 'Cancel'.

**Comment by dshubhadeep** [comment]
Hi @carolinaknoll, I would like to work on this

**Comment by carolinaknoll** [comment]
Hi, @dshubhadeep! Okay, I will add a 'taken' label to this issue so that you can safely work on it.

You can create your pull request in October when Hacktoberfest begins, if you would like it to count towards your shirt. :octocat: 

Thanks for helping the project! 😄

**Comment by dshubhadeep** [comment]
Thank you 😊
I have some pending projects at the moment. 
We can discuss the requirements once Hacktoberfest begins, if that's okay with you.

**Comment by carolinaknoll** [comment]
Yes, no problem. You don't need to rush it, just comment back when you can and we can discuss it further next month. 

Thank you! 😄

**Comment by akashsark** [comment]
Hi @carolinaknoll, I would like to work on this

**Comment by carolinaknoll** [comment]
Hi @akashsark!

Thank you for your interest, but this issue is already taken by @dshubhadeep. 

This means that you cannot work on it, since it is already assigned to @dshubhadeep.

In any case, thank you for your interest on contributing to the project! 😄

**Comment by dshubhadeep** [comment]
Hi @carolinaknoll, I will start working on the first 2 issues.
What format should the exported file be in ? JSON ?
Should the import/export feature be added to the saved-item component ?

**Comment by carolinaknoll** [comment]
Hi @dshubhadeep, thanks for your comment!

Yes, JSON format seems fantastic.

About the import/export, I think it will look okay if it is a button inside the saved-items panel. If for some reason it doesn't, there is always space on the navigation bar where you can put it.

However, for the file structure, I believe that it will be better being a individual component (and not linked together with saved-items). But, again, if it seems too complicated that way, you can add it to the saved-items and the code can be refactored in the future, if needed.

Thank you for spending your time to contribute to the project! 😄

**Comment by dshubhadeep** [comment]
Cool, I'll start working on it.
And there is a bug where an item can be saved even if it's already present in the list, thus it appears multiple times. 
I can work on it, if that's okay with you.

**Comment by carolinaknoll** [comment]
Hi @dshubhadeep, well spotted! I had forgotten about this bug, nice that you found it! 😄 

It will be awesome for you to work on it. If you would like, you can create an issue or a different pull request for it. 

Thank you! 🚀

**Comment by dshubhadeep** [comment]
No problem 👍 
I'll create a different pull request for that.

**Comment by dshubhadeep** [comment]
@carolinaknoll I have submitted a PR, let me know if there are any changes.

**Comment by carolinaknoll** [comment]
I have commented on the PR, this feature looks great!

I have merged your changes, and will be closing this issue. 

Thank you for your contribution! 😄
