### ISSUE TITLE
[SavedItems] Show amount of saved bookmarked and saved seen items on panel

### ISSUE THREAD

**Issue by carolinaknoll** [carolinaknoll/awesome-gamified#12]
The SavedItems panel should show the current number of saved bookmarks and saved seen items.

This information can be shown in a `<p>` element for each.

As an example: 

`<p>Bookmarked items: 10</p>`
`<p>Seen items: 15</p>`

As an optional, feel free to add a font-awesome icon to each of them, if you would like. But if you see that there is no need for them, this is okay too! 😄 

Thank you! 🎉 ✨

**Comment by VadimDez** [comment]
Hi @carolinaknoll can I help you with this?

**Comment by carolinaknoll** [comment]
Sure! 😄 

I will label this issue as taken so that you can safely work on it.

You can open your pull request in October, during Hacktoberfest, if you want to get your shirt.

Thank you for taking your time to help this project! 🚀 👓
